### ISSUE TITLE
Label field should be required

### ISSUE THREAD

**Issue by justinjjvanderhooft** [iomega/paired-data-form#73]
It looks like the "label" field is not required whereas we need it in the linking stage. If we set it to "required" it will throw up an error when people try "preview" so they know they have to add it.

**Comment by sverhoeven** [comment]
To clarify with an example:
1. Create a genome without filling in the genome label field
2. Create another genome without filling in the genome label field
3. Create a Genome-Metabolome link

The Genome select field will show a single empty field.

Expected behavior is an validation error that the labels should be unique and not be falsy (empty string or undefined).

**Comment by sverhoeven** [comment]
Validation is now only performed for the whole form when pressing submit or preview buttons.

Validation of the label should also be performed when the select fields in the links table are opened.
